spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  mail:
    host: smtp.gmail.com
    username: ali.guseynof2503@gmail.com
    password: wdtvlxfmkrzogplt
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"


